[package]
name = "spotify-controller"
version = "0.1.0"
edition = "2018"

[dependencies]
#rspotify = "0.10.0"
#failure = "0.1.8"
rspotify = { git = "https://github.com/ramsayleung/rspotify", features = ["cli"] }
tokio = { version = "1.10.0", features = ["full"] }
